<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>Kwerty.DviZe.Win.Wnf</RootNamespace>
    <Version>1.0.0.0</Version>
    <Copyright>Copyright (c) 2026 Kwerty</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ConfigureAwaitChecker.Analyzer" Version="5.0.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DviZe.Common\src\DviZe.Common.csproj" />
  </ItemGroup>
</Project>
